apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: gitlab-publish-wiki-page
  labels:
    app.kubernetes.io/version: "0.0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: gitlab, publish, wiki
    tekton.dev/displayName: "gitlab publish wiki"

spec:
  description: >-
    This task publish a wiki page on gitlab
  # workspaces:
  #   - name: source

  params:
    - name: IMAGE
      description: The image used by the task
      type: string
      default: neo9sas/devops-tools:v1.5.0
    - name: GROUP_ID
      description: the project id on gitlab
      default: ""
    - name: GITLAB_URL
      type: string
      description: "The gitlab url"
    - name: WIKI_NAME
      type: string
    - name: DATA
      type: string
    - name: DATA_TYPE
      type: string
      description: Accept Markdown and HTML

  steps:
    - name: exec-script
      image: $(params.IMAGE)
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash"]
      env:
        - name: GITLAB_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ (index .Values.releases "tekton" "secrets" "git-api-token" "secretRef" "name") }}
              key: {{ (index .Values.releases "tekton" "secrets" "git-api-token" "secretRef" "key") }}
      args:
        - -c
        - |
          #!/usr/bin/env bash
          report=""
          if [ $(params.DATA_TYPE) = "HTML" ]
          then
            npm install --silent -g to-markdown-cli
            echo $(params.DATA) | html2md -g -o report.md
            $report=(cat report.md)
          else
            $report=$(params.DATA)
          fi

          responseCode=$(curl -s -o /dev/null -w "%{http_code}" --request GET --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" "$(params.GITLAB_URL)/groups/$(params.GROUP_ID)/wikis/$(params.WIKI_NAME)")
          if [ $responseCode = 200 ]
          then
            curl --request PUT --data "format=markdown&content=$(params.WIKI_NAME)&title=$report" --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" "$(params.GITLAB_URL)/groups/$(params.GROUP_ID)/wikis/$(params.WIKI_NAME)"
          else
            curl --request POST --data "format=markdown&title=$(params.WIKI_NAME)&content=$report" --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" "$(params.GITLAB_URL)/groups/$(params.GROUP_ID)/wikis"
          fi
