apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ts-lint
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: linter
    tekton.dev/displayName: "TypeScript linter"
spec:
  description: >-
    This task can be used to perform lint check on TypeScript files
  workspaces:
    - name: shared-workspace
      description: A workspace that contains the fetched git repository.
  params:
    - name: args
      type: array
      description: extra args needs to append
      default: ["--help"]
  steps:
    - name: lint-typescript
      image: docker.io/pipelinecomponents/tslint:0.14.1@sha256:85c7dd3f2b6d411fd01b8ad489afd20fb6ac4b2560f29ca506782c1f1a8d9b45 #tag: 0.14.1
      workingDir: $(workspaces.shared-workspace.path)
      command:
        - tslint
      args:
        - $(params.args)
