{{ if (eq .Values.scaling.enabled true) }}
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: logging-hpa.rules
spec:
  groups:
  - name: logging-hpa.rules
    rules:
    - expr: (node_filesystem_size_bytes{container="buffer-metrics-sidecar",mountpoint="/buffers"}-node_filesystem_free_bytes{container="buffer-metrics-sidecar",mountpoint="/buffers"})/node_filesystem_size_bytes{container="buffer-metrics-sidecar",mountpoint="/buffers"}
      record: buffer_space_usage_ratio
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: logging-fluentd
spec:
  scaleTargetRef:
    name: logging-fluentd
    kind: StatefulSet
    apiVersion: apps/v1
  triggers:
  - type: prometheus
    metricType: Value # https://keda.sh/docs/2.8/faq/ => search HPA
    metadata:
      serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
      metricName: buffer_space_usage
      # threshold: '0.26' # ~80 for 6
      threshold: '0.80' # ~80 for 6
      query: avg(buffer_space_usage_ratio)
  minReplicaCount:  1                                # Optional. Default: 0
  maxReplicaCount:  10                              # Optional. Default: 100
{{ end }}
