apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: core-tag
spec:
  params:
  - name: build-format
  - name: build-tool
  - name: git-url
  - name: git-project-name
  - name: git-branch
  - name: git-branch-sanitized
  - name: git-sha
  - name: project-id
  - name: container-images-repository
  - name: sonar-url
  - name: git-api-endpoint
  - name: continuous-delivery-namespace
  - name: continuous-delivery-branch
  - name: debug-sleep
  - name: container-image-tag
  - name: publish
  - name: notify-slack
  - name: tekton-url
  - name: dockerfile
  - name: auto-merge
  - name: apply
  - name: apply-dry-run
  - name: kube-core-image

  # - name: run-namespace
  # - name: run-name-template
  - name: run-storage-requests
  - name: run-service-account
  # - name: node-version
  # - name: node-tests-image
  # - name: run-tests
  # - name: chart-name
  # - name: chart-version

  - name: cluster-repository-name
  - name: cluster-repository-url
  - name: cluster-repository-ref
  - name: cluster-repository-path
  - name: git-tag
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: {{ .Values.cluster.delivery.config.run.nameTemplate | quote }}
      namespace: {{ .Values.cluster.delivery.config.run.namespace | quote }}
    spec:
      serviceAccountName: $(tt.params.run-service-account)
      workspaces:
      - name: ws
        volumeClaimTemplate:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: $(tt.params.run-storage-requests)
      pipelineRef:
        name: core-tag
      params:
      - name: debug
        value: "true"
      - name: build-format
        value: $(tt.params.build-format)
      - name: git-url
        value: $(tt.params.git-url)
      - name: git-project-name
        value: $(tt.params.git-project-name)
      - name: git-branch
        value: $(tt.params.git-branch)
      - name: git-sha
        value: $(tt.params.git-sha)
      - name: project-id
        value: $(tt.params.project-id)
      - name: container-images-repository
        value: $(tt.params.container-images-repository)
      - name: sonar-url
        value: $(tt.params.sonar-url)
      - name: git-api-endpoint
        value: $(tt.params.git-api-endpoint)
      - name: continuous-delivery-namespace
        value: $(tt.params.continuous-delivery-namespace)
      - name: continuous-delivery-branch
        value: $(tt.params.continuous-delivery-branch)
      - name: debug-sleep
        value: $(tt.params.debug-sleep)
      - name: container-image-tag
        value: $(tt.params.container-image-tag)
      - name: publish
        value: $(tt.params.publish)
      - name: notify-slack
        value: $(tt.params.notify-slack)
      - name: tekton-url
        value: $(tt.params.tekton-url)
      - name: build-tool
        value: $(tt.params.build-tool)
      - name: dockerfile
        value: $(tt.params.dockerfile)
      - name: auto-merge
        value: $(tt.params.auto-merge)
      - name: apply
        value: $(tt.params.apply)
      - name: apply-dry-run
        value: $(tt.params.apply-dry-run)
      - name: kube-core-image
        value: $(tt.params.kube-core-image)
      # - name: node-version
      #   value: $(tt.params.node-version)
      # - name: node-tests-image
      #   value: $(tt.params.node-tests-image)
      # - name: run-tests
      #   value: $(tt.params.run-tests)
      # - name: chart-name
      #   value: $(tt.params.chart-name)
      # - name: chart-version
      #   value: $(tt.params.chart-version)
      - name: cluster-repository-name
        value: $(tt.params.cluster-repository-name)
      - name: cluster-repository-url
        value: $(tt.params.cluster-repository-url)
      - name: cluster-repository-ref
        value: $(tt.params.cluster-repository-ref)
      - name: cluster-repository-path
        value: $(tt.params.cluster-repository-path)
      - name: git-tag
        value: $(tt.params.git-tag)
