policies:
  all:
    validationFailureAction: audit
  # Mutate
  who-created-this:
    enabled: true
  add-default-resources:
    enabled: true
  always-pull-images:
    enabled: false
  mutate-termination-grace-period-seconds:
    enabled: true
  add-namespace-node-affinity:
    enabled: true
  add-namespace-node-selector:
    enabled: true
  add-namespace-pdb:
    enabled: true
  add-namespace-priority-class:
    enabled: true
  label-namespaces:
    enabled: true
  add-node-taint:
    enabled: true
  add-node-affinity:
    enabled: true
  add-node-selector:
    enabled: true
  add-pdb-max-unavailable:
    enabled: true
  add-pdb-min-available:
    enabled: true
  add-safe-to-evict:
    enabled: true
  insert-self-hard-pod-antiaffinity:
    enabled: true
  insert-self-soft-pod-antiaffinity:
    enabled: true
  remove-node-selector:
    enabled: true
  # Validate
  deny-empty-ingress-host:
    enabled: true
  ingress-host-match-tls:
    enabled: true
  restrict-ingress-classes:
    enabled: true
  restrict-ingress-defaultbackend:
    enabled: true
  restrict-ingress-wildcard:
    enabled: true
  require-pod-probes:
    enabled: true
  validate-probes:
    enabled: true
  prevent-naked-pods:
    enabled: true
  deny-default-namespace:
    enabled: true
  protect-node-taints:
    enabled: true
  restrict-node-selector:
    enabled: true
  deny-exec:
    enabled: true
  deny-external-ips:
    enabled: true
  deny-latest-tag:
    enabled: true
  deny-loadbalancer:
    enabled: true
  deny-nodeport:
    enabled: true
  enforce-resources-ratio:
    enabled: true


namespace: {}
  # nodeSelector:
  # - tekton-pipelines
  # - predator
  # nodeAffinity:
  # - tekton-pipelines
  # - validation
  # - production
  # priorityClass:
  # - production
  # pdb:
  # - production
  # denyExec:
  # - production
  # labels: {}

node:
  excludeTaints:
  - main
  - safety
