{{ $policyName := "restrict-node-selector" }}
{{ if (index .Values.policies $policyName "enabled") }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: restrict-node-selector
  annotations:
    policies.kyverno.io/title: Restrict node selection
    policies.kyverno.io/category: Sample
    policies.kyverno.io/subject: Pod
    policies.kyverno.io/description: >-
      The Kubernetes scheduler uses complex logic to determine the optimal placement
      for new Pods. Users who have access to set certain fields in a Pod spec
      may sidestep this logic which in many cases is undesirable. This policy
      prevents users from targeting specific Nodes for scheduling of Pods by
      prohibiting the use of the `nodeName` fields.
spec:
  failurePolicy: {{ coalesce (index .Values.policies $policyName "failurePolicy") .Values.policies.all.failurePolicy }}
  validationFailureAction: {{ coalesce (index .Values.policies $policyName "validationFailureAction") .Values.policies.all.validationFailureAction }}
  # background: true
  rules:
  - name: restrict-node-selector
    match:
      resources:
        kinds:
        - Pod
    exclude:
      clusterRoles:
      - cluster-admin
    validate:
      message: Setting the nodeSelector field is prohibited.
      pattern:
        spec:
          X(nodeSelector): "null"
  - name: restrict-nodename
    match:
      resources:
        kinds:
        - Pod
    exclude:
      clusterRoles:
      - cluster-admin
    validate:
      message: Setting the nodeName field is prohibited.
      pattern:
        spec:
          X(nodeName): "null"
  - name: restrict-tolerations
    match:
      resources:
        kinds:
        - Pod
    exclude:
      clusterRoles:
      - cluster-admin
    validate:
      message: Setting the nodeName field is prohibited.
      pattern:
        spec:
          X(tolerations): "null"
  - name: restrict-affinity
    match:
      resources:
        kinds:
        - Pod
    exclude:
      clusterRoles:
      - cluster-admin
    validate:
      message: Setting the nodeName field is prohibited.
      pattern:
        spec:
          X(affinity): "null"
{{ end }}
