
git:
  tagName: "v${version}"
  commitMessage: "release: v${version}"
  requireCommits: true
  requireCleanWorkingDir: false
  addUntrackedFiles: false

  changelog: |-
    npx auto-changelog -o CHANGELOG.md --commit-limit false --remote=origin -u --hide-credit --release-summary --latest-version ${version} --template=compact

npm: false

hooks:
  "after:bump": 'sh -c "kube-core scripts:exec dev_utils_bump ${version}" && npx auto-changelog -o CHANGELOG.md --commit-limit false --remote=origin -u --hide-credit --release-summary --latest-version ${version} --template=compact && cd ./cli && yarn && yarn prepack && yarn postpack'
