apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
  - path: releases/base
    contents:
      # Base Releases
      - path: goldilocks
        helmChart:
          name: goldilocks
          version: 6.5.5
          repository:
            url: https://charts.fairwinds.com/stable
      - path: trivy
        helmChart:
          name: trivy
          version: 0.7.0
          repository:
            url: https://aquasecurity.github.io/helm-charts
      - path: mongodb-managed
        helmChart:
          name: mongodb-managed
          version: 0.6.3
          repository:
            url: https://neo9.github.io/helm-charts
      - path: postgres-managed
        helmChart:
          name: postgres-managed
          version: 0.2.3
          repository:
            url: https://neo9.github.io/helm-charts
      - path: postgres-operator
        helmChart:
          name: postgres-operator
          version: 1.10.0
          repository:
            url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
      - path: rabbitmq-managed
        helmChart:
          name: rabbitmq-managed
          version: 0.4.1
          repository:
            url: https://neo9.github.io/helm-charts
      - path: node-problem-detector
        helmChart:
          name: node-problem-detector
          version: 2.3.4
          repository:
            url: https://charts.deliveryhero.io/
      - path: mongodb-community-operator
        helmChart:
          name: community-operator
          version: 0.7.6
          repository:
            url: https://mongodb.github.io/helm-charts
      - path: descheduler
        helmChart:
          name: descheduler
          version: 0.26.1
          repository:
            url: https://kubernetes-sigs.github.io/descheduler/
      - path: prometheus-pushgateway
        helmChart:
          name: prometheus-pushgateway
          version: 2.1.3
          repository:
            url: https://prometheus-community.github.io/helm-charts
      - path: kyverno-policies
        helmChart:
          name: kyverno-policies
          version: 2.7.2
          repository:
            url: https://kyverno.github.io/kyverno/
      - path: kyverno
        helmChart:
          name: kyverno
          version: 2.7.2
          repository:
            url: https://kyverno.github.io/kyverno/
      - path: chaos-mesh
        helmChart:
          name: chaos-mesh
          version: 2.5.2
          repository:
            url: https://charts.chaos-mesh.org
      - path: sloth
        helmChart:
          name: sloth
          version: 0.7.0
          repository:
            url: https://slok.github.io/sloth
      - path: pyrra
        helmChart:
          name: pyrra
          version: 0.7.0
          repository:
            url: https://rlex.github.io/helm-charts
      - path: prometheus-adapter
        helmChart:
          name: prometheus-adapter
          version: 4.2.0
          repository:
            url: https://prometheus-community.github.io/helm-charts
      - path: keda
        helmChart:
          name: keda
          version: 2.10.2
          repository:
            url: https://kedacore.github.io/charts
      - path: logging-operator
        helmChart:
          name: logging-operator
          version: 3.17.10
          repository:
            url: https://kubernetes-charts.banzaicloud.com
      - path: cert-manager
        helmChart:
          name: cert-manager
          version: v1.11.1
          repository:
            url: https://charts.jetstack.io
      - path: chartmuseum
        helmChart:
          name: chartmuseum
          version: 3.9.3
          repository:
            url: https://chartmuseum.github.io/charts
      - path: crossplane
        helmChart:
          name: crossplane
          version: 1.12.1
          repository:
            url: https://charts.crossplane.io/stable
      - path: eck-operator
        helmChart:
          name: eck-operator
          version: 2.7.0
          repository:
            url: https://helm.elastic.co
      - path: estafette-k8s-node-compactor
        helmChart:
          name: estafette-k8s-node-compactor
          version: 1.1.0
          repository:
            url: https://helm.estafette.io
      - path: estafette-vulnerability-scanner
        helmChart:
          name: estafette-vulnerability-scanner
          version: 0.1.16
          repository:
            url: https://helm.estafette.io
      - path: external-dns
        helmChart:
          name: external-dns
          version: 6.18.0
          repository:
            url: https://charts.bitnami.com/bitnami
      - path: forecastle
        helmChart:
          name: forecastle
          version: v1.0.125
          repository:
            url: https://stakater.github.io/stakater-charts
      - path: n9-api
        helmChart:
          name: n9-api
          version: 1.3.10
          repository:
            url: https://neo9.github.io/helm-charts
      - path: istio-rules-external-services
        helmChart:
          name: istio-rules-external-services
          version: 1.12.1
          repository:
            url: https://neo9.github.io/helm-charts
      - path: keycloak
        helmChart:
          name: keycloak
          version: 14.4.0
          repository:
            url: https://charts.bitnami.com/bitnami
      - path: kps
        helmChart:
          name: kps
          version: 1.1.1
          repository:
            url: https://neo9.github.io/helm-charts
      - path: kube-downscaler
        helmChart:
          name: kube-downscaler
          version: 0.7.1
          repository:
            url: https://charts.deliveryhero.io/
      - path: kube-fledged
        helmChart:
          name: kube-fledged
          version: v0.10.0
          repository:
            url: https://senthilrch.github.io/kubefledged-charts/
      - path: sonatype-nexus
        helmChart:
          name: sonatype-nexus
          version: 5.5.0
          repository:
            url: https://oteemo.github.io/charts
      - path: nginx
        helmChart:
          name: nginx
          version: 14.1.0
          repository:
            url: https://charts.bitnami.com/bitnami
      - path: nginx-ingress-controller
        helmChart:
          name: nginx-ingress-controller
          version: 9.5.1
          repository:
            url: https://charts.bitnami.com/bitnami
      - path: patch-operator
        helmChart:
          name: patch-operator
          version: v0.1.9
          repository:
            url: https://redhat-cop.github.io/patch-operator
      - path: polaris
        helmChart:
          name: polaris
          version: 5.7.3
          repository:
            url: https://charts.fairwinds.com/stable
      - path: predator
        helmChart:
          name: predator
          version: 1.6.3
          repository:
            url: https://zooz.github.io/helm/
      - path: reloader
        helmChart:
          name: reloader
          version: v1.0.24
          repository:
            url: https://stakater.github.io/stakater-charts
      - path: kubernetes-replicator
        helmChart:
          name: kubernetes-replicator
          version: 2.8.0
          repository:
            url: https://helm.mittwald.de
      - path: sonarqube
        helmChart:
          name: sonarqube
          version: 9.11.0
          repository:
            url: https://oteemo.github.io/charts
      - path: starboard-operator
        helmChart:
          name: starboard-operator
          version: 0.10.12
          repository:
            url: https://aquasecurity.github.io/helm-charts/
      - path: velero
        helmChart:
          name: velero
          version: 4.0.1
          repository:
            url: https://vmware-tanzu.github.io/helm-charts
      - path: zeebe-cluster-helm
        helmChart:
          name: zeebe-cluster-helm
          version: 1.3.7
          repository:
            url: https://helm.camunda.io
      - path: zeebe-operate-helm
        helmChart:
          name: zeebe-operate-helm
          version: 1.3.4
          repository:
            url: https://helm.camunda.io
      - path: external-secrets
        helmChart:
          name: external-secrets
          version: 0.1.0
          repository:
            url: https://charts.neo9.pro
      - path: kubernetes-secret-generator
        helmChart:
          name: kubernetes-secret-generator
          version: 3.4.0
          repository:
            url: https://helm.mittwald.de
      - path: kube-cleanup-operator
        helmChart:
          name: kube-cleanup-operator
          version: 1.0.4
          repository:
            url: http://charts.lwolf.org
      - path: rabbitmq-cluster-operator
        helmChart:
          name: rabbitmq-cluster-operator
          version: 3.2.10
          repository:
            url: https://charts.bitnami.com/bitnami
      - path: sealed-secrets
        helmChart:
          name: sealed-secrets
          version: 2.8.2
          repository:
            url: https://bitnami-labs.github.io/sealed-secrets
      - path: mongodb-atlas-operator
        helmChart:
          name: mongodb-atlas-operator
          version: 1.7.2
          repository:
            url: https://mongodb.github.io/helm-charts
      - path: dex
        helmChart:
          name: dex
          version: 0.14.1
          repository:
            url: https://charts.dexidp.io
      - path: oauth2-proxy
        helmChart:
          name: oauth2-proxy
          version: 6.12.0
          repository:
            url: https://oauth2-proxy.github.io/manifests
      - path: kiali-operator
        helmChart:
          name: kiali-operator
          version: 1.67.0
          repository:
            url: https://kiali.org/helm-charts
      - path: jaeger-operator
        helmChart:
          name: jaeger-operator
          version: 2.43.0
          repository:
            url: https://jaegertracing.github.io/helm-charts
      - path: sidecar-cleaner
        helmChart:
          name: sidecar-cleaner
          version: 0.3.0
          repository:
            url: https://opensource.aoe.com/kubernetes-sidecar-cleaner/
      - path: container-registry-cleaner
        helmChart:
          name: container-registry-cleaner
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: container-registry-config
        helmChart:
          name: container-registry-config
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: container-registry-operator
        helmChart:
          name: container-registry-operator
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: estafette-gke-node-pool-shifter
        helmChart:
          name: estafette-gke-node-pool-shifter
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: estafette-gke-preemptible-killer
        helmChart:
          name: estafette-gke-preemptible-killer
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: ingress-access-operator
        helmChart:
          name: ingress-access-operator
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: minio-operator
        helmChart:
          name: minio-operator
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: minio-tenants
        helmChart:
          name: minio-tenants
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: mysql-backup
        helmChart:
          name: mysql-backup
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: opencost
        helmChart:
          name: opencost
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: sloop
        helmChart:
          name: sloop
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: tekton
        helmChart:
          name: tekton
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: tekton-catalog
        helmChart:
          name: tekton-catalog
          version: 0.1.0
          repository:
            url: https://neo9.github.io/helm-charts
      - path: tekton-logging
        helmChart:
          name: tekton-logging
          version: 0.1.1
          repository:
            url: https://neo9.github.io/helm-charts
      - path: app-extensions
        helmChart:
          name: app-extensions
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: cluster-logging
        helmChart:
          name: cluster-logging
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: cluster-policies
        helmChart:
          name: cluster-policies
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: cluster-rbac
        helmChart:
          name: cluster-rbac
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: env-config
        helmChart:
          name: env-config
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: flux
        helmChart:
          name: flux
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: flux-config
        helmChart:
          name: flux-config
          version: 0.2.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: flux-repository
        helmChart:
          name: flux-repository
          version: 0.2.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: imagecache
        helmChart:
          name: imagecache
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: istio-base
        helmChart:
          name: istio-base
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: istio-discovery
        helmChart:
          name: istio-discovery
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: istio-elasticsearch
        helmChart:
          name: istio-elasticsearch
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: istio-grafana
        helmChart:
          name: istio-grafana
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: istio-ingress-config
        helmChart:
          name: istio-ingress-config
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: istio-jaeger
        helmChart:
          name: istio-jaeger
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: istio-kiali
        helmChart:
          name: istio-kiali
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: istio-prometheus
        helmChart:
          name: istio-prometheus
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: jaeger-managed
        helmChart:
          name: jaeger-managed
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: kiali-managed
        helmChart:
          name: kiali-managed
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: linkerd
        helmChart:
          name: linkerd
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: logging-stack
        helmChart:
          name: logging-stack
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: namespace
        helmChart:
          name: namespace
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: node-initializer
        helmChart:
          name: node-initializer
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: priority-class
        helmChart:
          name: priority-class
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: raw
        helmChart:
          name: raw
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: slack-operator
        helmChart:
          name: slack-operator
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: system-jobs
        helmChart:
          name: system-jobs
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
      - path: test-logging
        helmChart:
          name: test-logging
          version: 0.1.0
          repository:
            url: https://kube-core.github.io/helm-charts
            # Local Releases

# - path: releases/crds
#   contents:
#   # CRD Releases
#   - path: kyverno-crds
#       helmChart:
#         name: kyverno-crds
#         version: v2.0.3
#         repository:
#           url: https://kyverno.github.io/kyverno/
#       includePaths: ["crds/*", "crds", "Chart.yaml", "values.yaml"]
