{{- define "app-extensions.gcp-targethttpproxy" -}}
{{- $name := (coalesce .value.name .key) }}
{{- $resourceName := (coalesce .value.resourceName .value.name .key) }}
apiVersion: compute.gcp.upbound.io/v1beta1
kind: TargetHTTPProxy
metadata:
  name: {{ $resourceName }}
  annotations:
    crossplane.io/external-name: {{ coalesce .value.externalName $name }}
spec:
  deletionPolicy: {{ coalesce .value.deletionPolicy "Orphan" }}
  forProvider:
    urlMap: {{ .value.urlMap | required ".value.urlMap is required" }}
    description: "{{ coalesce .value.description (printf "TargetHttpProxy of %s generated by kube-core for: %s/%s/%s" .value.urlMap .common.cluster.config.name .common.release.namespace ( coalesce .common.release.name $name)) }}"
  providerConfigRef:
    name: upbound-gcp
{{- end }}
