releases:
  cluster-logging:
    values:
      installCRDs: false
  eck-operator:
    values:
      installCRDs: false
  logging-stack:
    values:
      installCRDs: false
  patch-operator:
    values:
      enableCertManager: true
  sealed-secrets:
    values:
      crd:
        create: false
  trivy:
    values:
      image:
        tag: "0.32.1"
      trivy:
        debugMode: true
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
