releases:
  chartmuseum:
    values:
      extraArgs:
        - --cache-interval=1m
      gcp:
        secret:
          enabled: false
          key: chartmuseum-sa.json
          name: chartmuseum-sa
  cluster-logging:
    values:
      installCRDs: false
  eck-operator:
    values:
      installCRDs: false
  kubernetes-dashboard:
    values:
      resources:
        limits:
          cpu: 0.5
          memory: 200Mi
        requests:
          cpu: 50m
          memory: 100Mi
  logging-stack:
    values:
      installCRDs: false
  patch-operator:
    values:
      enableCertManager: true
  sealed-secrets:
    values:
      crd:
        create: false
  trivy:
    values:
      image:
        tag: "0.32.1"
      trivy:
        debugMode: true
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
