apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencost
  labels:
    app: opencost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencost
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: opencost
    spec:
      restartPolicy: Always
      serviceAccountName: opencost
      volumes:
        - name: persistent-configs
          persistentVolumeClaim:
            claimName: opencost-cost-analyzer
      containers:
        - image: quay.io/kubecost1/kubecost-cost-model:prod-1.99.0
          name: opencost
          resources:
            requests:
              cpu: "10m"
              memory: "55M"
            limits:
              cpu: "999m"
              memory: "1G"
          volumeMounts:
            - name: persistent-configs
              mountPath: /var/configs
          env:
            - name: LOG_FORMAT
              value: "JSON"
            - name: PROMETHEUS_SERVER_ENDPOINT
              value: {{ .Values.kubeCost.prometheusServerEndpoint }} # The endpoint should have the form http://<service-name>.<namespace-name>.svc
            - name: CLOUD_PROVIDER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.kubeCost.cloudApiKeySecretName }}
                  key: apikey
              # value: {{ .Values.kubeCost.cloudProviderApiKey }} # The GCP Pricing API requires a key. This is supplied just for evaluation.
            - name: CLUSTER_ID
              value: {{ .Values.kubeCost.clusterId }} # Default cluster ID to use if cluster_id is not set in Prometheus metrics.
            - name: RELEASE_NAME
              value: opencost
            - name: KUBECOST_NAMESPACE
              value: opencost
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: CLUSTER_PROFILE
              value: production
            - name: KUBECOST_JOB_NAME
              value: "serviceMonitor/opencost/opencost/0"
            - name: THANOS_ENABLED
              value: "true"
            - name: THANOS_QUERY_URL
              value: {{ .Values.kubeCost.thanosQueryUrl }}
            - name: ETL_ENABLED
              value: "true"
            - name: ETL_RESOLUTION_SECONDS
              value: "300"
          imagePullPolicy: Always
        - image: quay.io/kubecost1/opencost-ui:prod-1.99.0
          name: opencost-ui
          resources:
            requests:
              cpu: "10m"
              memory: "55M"
            limits:
              cpu: "999m"
              memory: "1G"
          imagePullPolicy: Always