{{- if .Values.openUi.ingress.enabled }}
{{- $apiV1 := false -}}
{{- if and (.Capabilities.APIVersions.Has "networking.k8s.io/v1") (semverCompare ">= v1.19-0" .Capabilities.KubeVersion.Version) -}}
apiVersion: networking.k8s.io/v1
{{- $apiV1 = true -}}
{{- else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" -}}
apiVersion: networking.k8s.io/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: opencost-ui
  labels:
    app.kubernetes.io/name: opencost
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: ui
  {{- with .Values.openUi.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if and (.Values.openUi.ingress.ingressClassName) (semverCompare ">= v1.18-0" .Capabilities.KubeVersion.Version) }}
  ingressClassName: {{ .Values.openUi.ingress.ingressClassName }}
{{- end }}
{{- if .Values.openUi.ingress.tls }}
  tls:
  {{- range .Values.openUi.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.openUi.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          {{- if $apiV1 }}
          - path: {{ .path }}
            pathType: {{ .type }}
            backend:
              service:
                name: opencost
                port:
                  number: 9090
          {{- else }}
          - path: {{ .path }}
            backend:
              serviceName: opencost
              servicePort: 9090
          {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
