templates:
  release: &release
    config: {}
    enabled: false
    extraReleaseValues: []
    hooks: {}
    injectCoreValues: false
    jsonPatches: {}
    labels: {}
    manifests: []
    needs: []
    options:
      applyDefaultLabelsOnIngress: false
      applyDefaultAnnotationsOnIngress: false
      removeIngressClassAnnotation: false
      removeIngressClassName: false
      injectReloaderAnnotations: false
    release: {}
    secrets: {}
    patches: {}
    strategicMergePatches: {}
    transformers: {}
    values: {}
releases:
  cert-manager: *release
  chaos: *release
  chartmuseum: *release
  cluster-issuers: *release
  cluster-logging: *release
  container-registry-cleaner: *release
  container-registry-operator: *release
  crossplane: *release
  crossplane-buckets: *release
  crossplane-provider: *release
  crossplane-provider-config: *release
  eck-operator: *release
  efk: *release
  estafette-gke-node-pool-shifter: *release
  estafette-gke-preemptible-killer: *release
  estafette-k8s-node-compactor: *release
  estafette-vulnerability-scanner: *release
  external-dns: *release
  external-secrets: *release
  flux: *release
  forecastle: *release
  imagecache: *release
  ingress-access-operator: *release
  istio-base: *release
  istio-grafana: *release
  istio-ingress-sidecar: *release
  istio-kiali: *release
  istio-prometheus: *release
  istio-rules-external-services: *release
  istiod: *release
  keycloak: *release
  keycloak-dev: *release
  kps: *release
  kube-cleanup-operator: *release
  kube-downscaler: *release
  kube-fledged: *release
  kubernetes-dashboard: *release
  logging-gcs: *release
  logging-operator: *release
  logging-stack: *release
  metrics-server: *release
  minio-operator: *release
  minio-tenants: *release
  mongodb-operator: *release
  nexus: *release
  nginx: *release
  nginx-ingress-controller: *release
  nginx-istio-ingress-controller: *release
  node-initializer: *release
  patch-operator: *release
  polaris: *release
  predator: *release
  priority-class: *release
  rabbitmq-cluster: *release
  rabbitmq-config: *release
  rabbitmq-operators: *release
  reloader: *release
  replicator: *release
  sealed-secrets: *release
  secret-generator: *release
  sloop: *release
  sloth: *release
  sonarqube: *release
  starboard-operator: *release
  system-config: *release
  system-jobs: *release
  tekton: *release
  tekton-catalog: *release
  tekton-logging: *release
  velero: *release
  visitor-groups: *release
  zeebe: *release
  zeebe-operate: *release
