{{- define "cluster-logging.flowTemplate" }}


# Start - Setting variables
{{ if .cluster.logging.flows.config.forceDefault }}
{{ $_ := set .flow "forceDefault" true }}
{{ end }}

{{ if .cluster.logging.flows.config.forceDynamic }}
{{ $_ := set .flow "forceDynamic" true }}
{{ end }}
# End - Setting variables


apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: {{ .flowName }}
  labels:
    logging.kube-core.io/flow-name: "{{ .flowName }}"
    logging.kube-core.io/flow-type: "{{ .flowType }}"
spec:
  filters:
  # - enhanceK8s: {}
  - tag_normaliser:
      format: {{ .cluster.config.name }}/{{ .cluster.logging.flows.config.tagFormat }}
  - record_modifier:
      records:
      - cluster: {{ .cluster.config.name }}
        # TODO: Check if tag works {{/* tag: {{ .cluster.config.name }}/{{ .cluster.logging.flows.config.tagFormat }} # Doesn't work (check fluentd logs)*/}}
        log_type: {{ .flowName }}
  - parser: 
{{ toYaml .cluster.logging.flows.config.parser | indent 6 }}
  # TODO: Implement detectExceptions {{/* 
  # Check why it doesn't work and/or how to replace it with multiline parser config
  # - detectExceptions:
  #     multiline_flush_interval: "0.1"
  #     languages:
  #     #- all
  #     - java
  #     - js
  #     - csharp
  #     - python
  #     - go
  #     - ruby
  #     - php
#*/}}
{{- if .cluster.logging.flows.config.dedot }}
  # replaces dots in labels and annotations with dashes to avoid mapping issues (app=foo (text) vs. app.kubernetes.io/name=foo (object))
  # fixes error: existing mapping for [kubernetes.labels.app] must be of type object but found [text]
  # TODO: Check if it is better to use it or not, but only for performance. Fixing the underlying error (no label standards) should be done anyway.
  - dedot: 
      de_dot_separator: "_"
      de_dot_nested: true
{{- end }}
  - record_transformer:
      enable_ruby: true
      records:
      - tag: ${tag}
      - kubernetes.labels.app.kubernetes.io/name: ${record["kubernetes"]["labels"]["app"]}
      - kubernetes.labels.app.kubernetes.io/instance: ${record["kubernetes"]["labels"]["instance"]}
      - kubernetes.labels.app.kubernetes.io/version: ${record["kubernetes"]["labels"]["version"]}
      - kubernetes.labels.app.kubernetes.io/component: ${record["kubernetes"]["labels"]["component"]}
      - kubernetes.labels.app.kubernetes.io/istio: ${record["kubernetes"]["labels"]["istio"]}
      # Not sure if these work
      # - kubernetes.labels.app.kubernetes.io/part-of: ${record["kubernetes"]["labels"]["part-of"]}
      # - kubernetes.labels.app.kubernetes.io/managed-by: ${record["kubernetes"]["labels"]["managed-by"]}
      # - kubernetes.labels.app.kubernetes.io/created-by: ${record["kubernetes"]["labels"]["created-by"]}
{{ if .cluster.logging.flows.config.removeKeys }}
  - record_transformer:
      remove_keys: {{ .cluster.logging.flows.config.removeKeys }}
{{- end }}
{{- if .cluster.logging.flows.config.whitelist.enabled }}
  - record_modifier:
      whitelist_keys: {{ .cluster.logging.flows.config.whitelist.keys | quote }}
{{- end }}
{{- if .flow.extraFilters }}          
{{- toYaml .flow.extraFilters | indent 2 }}
{{- end }}
# If we nullout, if we don't have outputs and nullout, or if we didn't force neither dynamic or default outputs
{{- if .flow.stdout }}
  - stdout: {}
{{- end }}
  match: 
{{- if .flow.matchAll }}
  - select: {}
{{- else }}
{{- if .flow.namespaces }}
  - select:
      namespaces: {{ toYaml .flow.namespaces | nindent 8 }}
{{- end }}
  - select:
      labels:
        logging.kube-core.io/flow-name: {{ .flowName }}
{{- if .flow.extraMatchRules }}          
{{- toYaml .flow.extraMatchRules | indent 2 }}
{{- end }}
{{- end }}
{{ if (eq .cluster.logging.flows.config.legacyOutputRefs false) }}
  globalOutputRefs: 

  {{ if eq .flowType "default" }}

  {{ if .cluster.logging.integrations.gcs.enabled }}
  - {{ .flowType }}-gcs
  {{ end }}

  {{ if .cluster.logging.integrations.minio.enabled }}
  - {{ .flowType }}-minio
  {{ end }}

  {{ if .cluster.logging.integrations.s3.enabled }}
  - {{ .flowType }}-s3
  {{ end }}

  {{ if .cluster.logging.integrations.es.enabled }}
  - {{ .flowType }}-es
  {{ end }}

  {{ else if .flow.outputs }}
  {{ range .flow.outputs }}
  - {{ . }}
  {{ end }}

  {{ else }}

  {{ if (eq .cluster.logging.flows.simpleDynamicFlowsOutputMapping true)}}

  {{ if .cluster.logging.integrations.gcs.enabled }}
  - {{ .flowName }}-gcs
  {{ end }}
  {{ if .cluster.logging.integrations.minio.enabled }}
  - {{ .flowName }}-minio
  {{ end }}
  {{ if .cluster.logging.integrations.s3.enabled }}
  - {{ .flowName }}-s3
  {{ end }}
  {{ if .cluster.logging.integrations.es.enabled }}
  - {{ .flowName }}-es
  {{ end }}

  {{ end }}

{{ end }}
## LEGACY OUTPUTREF - DEPRECATED
{{ else if (eq .cluster.logging.flows.config.legacyOutputRefs true) }}
  globalOutputRefs: 
# Start - Force
{{ if or .flow.forceDynamic .flow.forceDefault }}
{{ if .flow.forceDynamic }}
  - {{ .flowName }}-minio
  - {{ .flowName }}-es
{{ end }}
{{ if .flow.forceDefault }}
  - default-minio
  - default-es
{{ end }}

# Start - Extra Outputs
{{- if .flow.extraOutputs }}
{{- range .flow.extraOutputs }}
  - {{ . }}
{{- end }}
{{- end }}
# End - Extra Outputs

{{ else if and .flow.outputs (not .flow.nullout) }} 
# End - Force

# Start - Custom & Default Outputs
{{- if (or .flow.outputs.dynamic .flow.outputs.default) }}
# Start - Dynamic Outputs
{{- if .flow.outputs.dynamic }}
{{- if .flow.outputs.dynamic.enabled }}
{{- if and .cluster.logging.stack.minio.enabled .flow.outputs.dynamic.minio }}
  - {{ .flowName }}-minio
{{- end }}
{{- if and .cluster.logging.stack.es.enabled .flow.outputs.dynamic.es }}
  - {{ .flowName }}-es
{{- end }}
{{- end }}
{{- end }}
# End - Dynamic Outputs

# Start - Default Outputs
{{- if .flow.outputs.default }}
{{- if .flow.outputs.default.enabled }}
{{- if and .cluster.logging.stack.minio.enabled .flow.outputs.default.minio }}
  - default-minio
{{- end }}
{{- if and .cluster.logging.stack.es.enabled .flow.outputs.default.es }}
  - default-es
{{- end }}
{{- end }}
{{- end }}
# End - Default Outputs
{{ end }}
# End - Custom & Default Outputs


# Start - Extra Outputs
{{- if .flow.extraOutputs }}
{{- range .flow.extraOutputs }}
  - {{ . }}
{{- end }}
{{- end }}
# End - Extra Outputs

{{ else }}
  # No outputs
  globalOutputRefs:
    - nullout
{{- end }}{{/*if .flow.outputs*/}}
{{ end }}
## LEGACY OUTPUTREF - DEPRECATED




{{- end }}{{/*Define End*/}}
