{{ if .Values.cluster.logging.flows.default.enabled }}
{{- template "cluster-logging.flowTemplate" (dict "cluster" .Values.cluster "cloud" .Values.cloud "flow" .Values.cluster.logging.flows.default "flowType" "default" "flowName" "default") }}
{{ end }}
