{{ if .Values.cluster.logging.integrations.events.enabled }}

apiVersion: logging.banzaicloud.io/v1beta1
kind: ClusterFlow
metadata:
  name: events
spec:
  filters:
  - tag_normaliser: {}
      # format: {{ .Values.cluster.config.name }}/...
  - record_modifier:
      records:
      - cluster: {{ .Values.cluster.config.name }}
        log_type: 'events'
  - parser:
{{ toYaml .Values.cluster.logging.flows.config.parser | indent 6 }}
{{ if .Values.cluster.logging.flows.config.removeKeys }}
  - record_transformer:
      remove_keys: {{ .Values.cluster.logging.flows.config.removeKeys }}
{{- end }}
{{- if .Values.cluster.logging.flows.config.whitelist.enabled }}
  - record_modifier:
      whitelist_keys: {{ .Values.cluster.logging.flows.config.whitelist.keys | quote }}
{{- end }}
  match:
  - select:
      labels:
        app.kubernetes.io/name: event-tailer
        app.kubernetes.io/instance: logging-event-tailer
  globalOutputRefs:
  {{ if .Values.cluster.logging.integrations.gcs.enabled }}
  - events-gcs
  {{ end }}
  {{ if .Values.cluster.logging.integrations.minio.enabled }}
  - events-minio
  {{ end }}
  {{ if .Values.cluster.logging.integrations.s3.enabled }}
  - events-s3
  {{ end }}
  {{ if .Values.cluster.logging.integrations.es.enabled }}
  - events-es
  {{ end }}
{{ end }}
