apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    k8s-app: metrics-server
    app: custom-metrics-server
    version: v0.3.6
  name: custom-metrics-server-v0.3.6
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: {{.Values.replicas}}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: metrics-server
      app: custom-metrics-server
      version: v0.3.6
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: docker/default
      creationTimestamp: null
      labels:
        k8s-app: metrics-server
        app: custom-metrics-server
        version: v0.3.6
      name: metrics-server
    spec:
      containers:
      - command:
        - /metrics-server
        - --metric-resolution=30s
        - --kubelet-port=10255
        - --deprecated-kubelet-completely-insecure=true
        - --kubelet-preferred-address-types=InternalIP,Hostname,InternalDNS,ExternalDNS,ExternalIP
        image: k8s.gcr.io/metrics-server-amd64:v0.3.6
        imagePullPolicy: IfNotPresent
        name: metrics-server
        ports:
        - containerPort: 443
          name: https
          protocol: TCP
        resources:
          limits:
            cpu: 44m
            memory: 63Mi
          requests:
            cpu: 44m
            memory: 63Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      - command:
        - /pod_nanny
        - --config-dir=/etc/config
        - --cpu=40m
        - --extra-cpu=0.5m
        - --memory=35Mi
        - --extra-memory=4Mi
        - --threshold=5
        - --deployment=metrics-server-v0.3.6
        - --container=metrics-server
        - --poll-period=300000
        - --estimator=exponential
        - --scale-down-delay=24h
        - --minClusterSize=5
        - --use-metrics=true
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        image: gke.gcr.io/addon-resizer:1.8.11-gke.0
        imagePullPolicy: IfNotPresent
        name: metrics-server-nanny
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 5m
            memory: 50Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: metrics-server-config-volume
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/os: linux
      {{- if.Values.nodeSelector }}
        {{ toYaml .Values.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if.Values.affinity }}
      affinity: {{ toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: metrics-server
      serviceAccountName: metrics-server
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - key: components.gke.io/gke-managed-components
        operator: Exists
      {{- if.Values.tolerations }}
      {{ toYaml .Values.tolerations | nindent 6 }}
      {{- end }}
      volumes:
      - configMap:
          defaultMode: 420
          name: metrics-server-config
        name: metrics-server-config-volume
