apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: parse-custom-config
  namespace: tekton-pipelines
spec:
  params:
  - name: container-images-repository
    value: {{ .Values.cloud.registry.hostname }}/{{ .Values.cloud.project }}

  - name: git-api-endpoint
    value: {{ .Values.git.api.url }}

  - name: cluster-repository-name
    value: {{ .Values.cluster.config.repository.name }}

  - name: cluster-repository-url
    value: {{ .Values.cluster.config.repository.url }}

  - name: cluster-repository-ref
    value: {{ .Values.cluster.config.repository.ref }}

  - name: cluster-repository-path
    value: {{ .Values.cluster.config.repository.path }}

  - name: sonar-url
    value: https://sonarqube.{{ .Values.cluster.config.domain }}/
  
  - name: tekton-url
    value: https://tekton-dashboard.tekton-pipelines.{{ .Values.cluster.config.domain }}

  - name: continuous-delivery-namespace
    value: {{ .Values.cluster.delivery.namespace | quote }}

  - name: continuous-delivery-branch
    value: {{ .Values.cluster.delivery.branch | quote }}

  - name: node-version
    value: {{ .Values.cluster.delivery.node.version | quote }}
  
  - name: node-tests-image
    value: {{ .Values.cluster.delivery.node.tests.image | quote }}
  
  - name: run-tests
    value: {{ .Values.cluster.delivery.config.run.tests | quote }}