# These values must be filled on consumer side !
core:
  packages:
    essentials:
      enabled: false
    logging:
      enabled: false
    monitoring:
      enabled: false
    crossplane:
      enabled: false
    estafette:
      enabled: false
    tekton:
      enabled: false
    kyverno:
      enabled: false
    istio:
      enabled: false
