core:
  releasesEnabled: true
  releasesRawEnabled: true
  releasesCustomEnabled: true
  namespacesEnabled: true
  globalLabelsEnabled: true
  globalHelmMetadataEnabled: true
  applicationsEnabled: false
  servicesEnabled: false
  clusterEnabled: false
