services:
  nginx-ingress-controller: {}
  nginx-istio-ingress-controller: {}
    # TODO: Implement values templating in these resources
    # scaling:
    #   enabled: true
    #   type: app-extensions
    #   minReplicaCount: 1
    #   maxReplicaCount: 20
    #   cpuAvg:
    #     enabled: true
    #   memoryAvg:
    #     enabled: true
    #   ingressAccessFreq:
    #     enabled: true
    #     threshold: 10
    #   serviceAccessFreq:
    #     enabled: true
    # monitoring:
    #   enabled: true
    #   cpuAvg:
    #     enabled: true
    #     container: controller
    #   memoryAvg:
    #     enabled: true
    #     container: controller
    #   ingressAccessFreq:
    #     enabled: true
    #     threshold: 10
    #   serviceAccessFreq:
    #     enabled: true
  flux-repository: {}
