apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: {{ coalesce .Values.name .Release.Name }}
  namespace: {{ coalesce .Values.namespace .Release.Namespace }}
  annotations:
    {{ if (eq .Values.pruneDisabled true) }}
    kustomize.toolkit.fluxcd.io/prune: disabled
    {{ end }}
    {{ if .Values.annotations }}
    {{ toYaml .Values.annotations | indent 4 }}
    {{ end }}
spec:
  gitImplementation: go-git
  interval: {{ coalesce .Values.interval "1m" }}
  ref:
    branch: {{ coalesce .Values.ref "main" }}
  secretRef:
    name: {{ coalesce .Values.secretName (printf "%s-git-ssh" (coalesce .Values.name .Release.Name)) }}
  timeout: {{ coalesce .Values.interval "60s" }}
  url: {{ .Values.repository }}
