apiVersion: v1
kind: Service
metadata:
  {{ if .Values.cluster.common.defaultServiceAnnotations }}
  annotations:
    {{ toYaml .Values.cluster.common.defaultServiceAnnotations | nindent 4 }}
  {{ end }}
  labels:
    name: console
    {{ if .Values.cluster.common.defaultServiceLabels }}
    {{ toYaml .Values.cluster.common.defaultServiceLabels | nindent 4 }}
    {{ end }}
  name: console
spec:
  ports:
  - name: http
    port: 9090
  - name: https
    port: 9443
  selector:
    app: console
