apiVersion: v1
kind: Service
metadata:
  annotations:
    {{ toYaml .Values.cluster.common.defaultServiceAnnotations | nindent 4 }}
  labels:
    name: console
    {{ toYaml .Values.cluster.common.defaultServiceLabels | nindent 4 }}
  name: console
spec:
  ports:
  - name: http
    port: 9090
  - name: https
    port: 9443
  selector:
    app: console