apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: app-pr-opened
spec:
  params:
  - name: pr-git-repo
    description: The git repo that triggered a PR
    type: string
    default: ""

  - name: pr-url
    description: The URL of the PR
    type: string
    default: ""

  - name: new-pr-url
    description: The URL of the PR after processing
    type: string
    default: ""

  - name: pr-source-branch
    description: The source branch of the PR
    type: string
    default: ""

  - name: pr-target-branch
    description: The target branch of the PR
    type: string
    default: ""

  workspaces:
  - name: ws
  tasks:
  - name: devops-tools
    taskRef:
      name: devops-tools
    params:
      - name: script
        value: |
          echo "pr-opened"
           

    workspaces:
      - name: input
        workspace: ws
      - name: output
        workspace: ws
      - name: source
        workspace: ws
      - name: data
        workspace: ws
    