apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.tap.linkerd.io
  labels:
    linkerd.io/extension: viz
    component: tap
spec:
  group: tap.linkerd.io
  version: v1alpha1
  groupPriorityMinimum: 1000
  versionPriority: 100
  service:
    name: tap
    namespace: linkerd-viz
  caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKVENDQWcyZ0F3SUJBZ0lRS25zNEdSUHJwTDZneEpBbXpScXh5akFOQmdrcWhraUc5dzBCQVFzRkFEQWUKTVJ3d0dnWURWUVFERXhOMFlYQXViR2x1YTJWeVpDMTJhWG91YzNaak1CNFhEVEl6TURJd09ESXpNVFV6TWxvWApEVEkwTURJd09ESXpNVFV6TWxvd0hqRWNNQm9HQTFVRUF4TVRkR0Z3TG14cGJtdGxjbVF0ZG1sNkxuTjJZekNDCkFTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTFF6UzFnYVNlMjh3VkhtckM1OU50dnkKSytkR1NVeG9tZSt0bGVBbCsrUnZKUy9yQTlNQ0JhUDNYS0tGc2ZWbmI5TG96QnZURlBHTEs4dDBSUTNsUnVvdQpWNmZJSkhuTFJMTDk0cTJ3WjF3NVNDN09qSDd2ODZMaC85Undpd2ZRcmliQ043SWg0V29nek5LUEpwZ3pJTW4wClFrZi9DTTFhYm9FM2Z1czRyN1F1bVRTWEhKM2l0OU5iZ2VMVDdlTG1KWmZtRXQvWGp0ekJ4T1lzK3QxK1BXVkgKcnBoYjNTcHA1TklxZDVCeDVkU05rdEtnWUNnSEFWNVRXb3FyVFRYS0RwN0xsRE95dFhyMVJSVElZUnd1STRyWAoxb2F2N0lhVjhLTG1wQVlpZVRVVTQ0VmdJNHNvOG9xU1BQR052NkRiVE94YWR3WXMxVzZRYTNVTzBjS2JOaTBDCkF3RUFBYU5mTUYwd0RnWURWUjBQQVFIL0JBUURBZ1dnTUIwR0ExVWRKUVFXTUJRR0NDc0dBUVVGQndNQkJnZ3IKQmdFRkJRY0RBakFNQmdOVkhSTUJBZjhFQWpBQU1CNEdBMVVkRVFRWE1CV0NFM1JoY0M1c2FXNXJaWEprTFhacAplaTV6ZG1Nd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLSWtVN0FBZTJLWk9pVHZrMG11TklJbmZpcmdRa3BRCi9oUTNFQmNPcWcwSUw2bllrcnpoMXp5b01XblB1YjJPVk1jT0N4b2JiQVpNQXJiM1ZPazlNYWcxWDlWbXVwRlEKSFg5TnMzZ0hxai90bi95SndNVVNXMnl1N0FiU0FkeDB4dCt0RWFGblorVWpEVklFUThRWWQwZ3ZnRXloN3JYUQpRMURvZjN6ZnN0M1JudjU3bGtqWGY5SjFPS0RXeFdQM3JTMTJhNkhxSTdOYmI5YVliSTNPcGRVTSt4NVIwVDV1Ck1kQW9sZmlMV1laaG9XdmpISm1PL2plb1JIUmFCTXFzNGo5cXFWa1VQd083TkdCZHVGYmtaelNYbVIwUW15QloKS1BSdHRDc1ZLU1A2aDdWV2hlNXZUZVViME5ZT0luYXAwZjluNlN3WVlnV25rTit2d2dSMWZzbz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==

