{{- include "crossplane-cloud.add-release-metadata-to-values" . -}}

{{ if .Values.projectIAMMembers }}
{{ range $key, $value := .Values.projectIAMMembers }}

{{ $ressource := dict "key" $key "value" $value }}
{{ $globalpick := pick $.Values "patch" "cloud" "cluster" "release" }}
{{ $commonvalues := dict "common" $globalpick }}
{{ $mergedvalues := deepCopy $commonvalues | mustMerge $ressource }}

---
{{ include "crossplane-cloud.projectiammember" $mergedvalues }}
{{ end }}
{{ end }}
