applicationsConfig:
  options:
    forceNamespace: false
    forceNamespaceNodeSelector: false
    forceNamespaceNodeAffinity: false
    applyDefaultAnnotationsOnIngress: false
    applyDefaultLabelsOnIngress: false
    injectClusterLoggingLabel: false
    injectDefaultIngressClassName: false
    injectReloaderAnnotations: false
    patchIngresses: false
    injectIngressHost: false
    injectIngressTls: false
    forceNamespaceClusterIssuer: false
applications:
  app:
    enabled: false
