cluster:
  specs:
    autoscaling:
      profile: OPTIMIZE_UTILIZATION # or BALANCED
      resourceLimits:
        - resourceType: 'cpu'
          minimum: 8
          maximum: 32
        - resourceType: 'memory'
          minimum: 32
          maximum: 128
      management:
        autoRepair: true
        autoUpgrade: true
      diskSizeGb: 100
    kubernetes:
      version: 1.21
    nodes:
      main:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 8
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        node_metadata: "UNSPECIFIED"
      safety:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 8
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: false
        node_metadata: "UNSPECIFIED"
      system:
        machine_type: "e2-micro"
        min_count: 2
        max_count: 10
        local_ssd_count: 0
        disk_size_gb: 30
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        initial_node_count: 1
        node_metadata: "UNSPECIFIED"
      production:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 1
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        node_metadata: "UNSPECIFIED"
      monitoring:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 1
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        node_metadata: "UNSPECIFIED"
      logging:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 1
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        node_metadata: "UNSPECIFIED"
      data:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 1
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        node_metadata: "UNSPECIFIED"
      search:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 1
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        node_metadata: "UNSPECIFIED"
      web:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 1
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        node_metadata: "UNSPECIFIED"
      batch:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 1
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        node_metadata: "UNSPECIFIED"
      predator:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 1
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        node_metadata: "UNSPECIFIED"
      sf:
        machine_type: "n2-custom-8-24576"
        initial_node_count: 0
        min_count: 0
        max_count: 1
        local_ssd_count: 0
        disk_size_gb: 100
        disk_type: "pd-ssd"
        image_type: "COS"
        auto_repair: true
        auto_upgrade: true
        preemptible: true
        node_metadata: "UNSPECIFIED"
  logging:
    flows:
      flows:
      - name: app
      - name: cluster
    integrations:
      es:
        enabled: true
    stack:
      es:
        nodes:
          storageClass: gcp-sc-retain-wait-ssd
          affinity: {}
          nodeSelector: {}
          tolerations:
          - key: "type"
            operator: "Equal"
            value: "search"
            effect: "NoSchedule"
          - key: "type"
            operator: "Equal"
            value: "search"
            effect: "NoExecute"
          - key: "type"
            operator: "Equal"
            value: "logging"
            effect: "NoSchedule"
          - key: "type"
            operator: "Equal"
            value: "logging"
            effect: "NoExecute"
          - key: "type"
            operator: "Equal"
            value: "monitoring"
            effect: "NoSchedule"
          - key: "type"
            operator: "Equal"
            value: "monitoring"
            effect: "NoExecute"
      kibana:
        enabled: true
      minio:
        enabled: true
      fluentd:
        buffer:
          storageClass: gcp-sc-retain-wait-ssd
        tolerations:
        - key: "type"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
        - key: "type"
          operator: "Equal"
          value: "monitoring"
          effect: "NoExecute"
        affinity: {}
      fluentbit:
        enabled: true
        tolerations:
        - key: "type"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
        - key: "type"
          operator: "Equal"
          value: "monitoring"
          effect: "NoExecute"
        - key: "type"
          operator: "Equal"
          value: "production"
          effect: "NoSchedule"
        - key: "type"
          operator: "Equal"
          value: "production"
          effect: "NoExecute"
        # - key: "type"
        #   operator: "Equal"
        #   value: "system"
        #   effect: "NoSchedule"
        # - key: "type"
        #   operator: "Equal"
        #   value: "system"
        #   effect: "NoExecute"
        affinity: {}

  delivery:
    namespace: apps
    branch: main
    config:
      autoMerge: "false"
      kubeCoreImage: neo9sas/kube-core:latest
      apply:
        enabled: false
        dry: ""
    node:
      version: "16.14.2"
      tests:
        image: "node:16.14.2"
