rabbitmq:
  cluster:
    serviceType: LoadBalancer
    visitorGroupBasedSourceRanges: true
    loadBalancerSourceRanges: |-
      ["0.0.0.0/0"]
    replicas: 3
    storageSize: 10Gi
    storageClass: gcp-sc-retain-wait-ssd
    additionalConfig: |
      log.console.level = error
