releases:
  cert-manager:
    enabled: false
  chaos-mesh:
    enabled: false
  chartmuseum:
    enabled: false
  cluster-issuers:
    enabled: false
  cluster-logging:
    enabled: false
  container-registry-cleaner:
    enabled: false
  container-registry-config:
    enabled: false
  container-registry-operator:
    enabled: false
  crossplane:
    enabled: false
  crossplane-buckets:
    enabled: false
  crossplane-cloud:
    enabled: false
  crossplane-provider:
    enabled: false
  crossplane-provider-config:
    enabled: false
  eck-operator:
    enabled: false
  efk:
    enabled: false
  estafette-gke-node-pool-shifter:
    enabled: false
  estafette-gke-preemptible-killer:
    enabled: false
  estafette-k8s-node-compactor:
    enabled: false
  estafette-vulnerability-scanner:
    enabled: false
  external-dns:
    enabled: false
  external-secrets:
    enabled: false
  flux:
    enabled: false
  flux-config:
    enabled: false
  forecastle:
    enabled: false
  imagecache:
    enabled: false
  ingress-access-operator:
    enabled: false
  istio-base:
    enabled: false
  istio-grafana:
    enabled: false
  istio-ingress-sidecar:
    enabled: false
  istio-kiali:
    enabled: false
  istio-prometheus:
    enabled: false
  istio-rules-external-services:
    enabled: false
  istiod:
    enabled: false
  keda:
    enabled: false
  keycloak:
    enabled: false
  keycloak-dev:
    enabled: false
  kps:
    enabled: false
  kube-cleanup-operator:
    enabled: false
  kube-downscaler:
    enabled: false
  kube-fledged:
    enabled: false
  kubernetes-dashboard:
    enabled: false
  logging-gcs:
    enabled: false
  logging-operator:
    enabled: false
  logging-stack:
    enabled: false
  metrics-server:
    enabled: false
  minio-operator:
    enabled: false
  minio-tenants:
    enabled: false
  mongodb-atlas-operator:
    enabled: false
  mongodb-operator:
    enabled: false
  nexus:
    enabled: false
  nginx:
    enabled: false
  nginx-ingress-controller:
    enabled: false
  nginx-istio-ingress-controller:
    enabled: false
  node-initializer:
    enabled: false
  patch-operator:
    enabled: false
  polaris:
    enabled: false
  predator:
    enabled: false
  priority-class:
    enabled: false
  prometheus-adapter:
    enabled: false
  rabbitmq-operators:
    enabled: false
  reloader:
    enabled: false
  replicator:
    enabled: false
  sealed-secrets:
    enabled: false
  secret-generator:
    enabled: false
  sloop:
    enabled: false
  sloth:
    enabled: false
  sonarqube:
    enabled: false
  starboard-operator:
    enabled: false
  system-config:
    enabled: false
  system-jobs:
    enabled: false
  tekton:
    enabled: false
  tekton-catalog:
    enabled: false
  tekton-logging:
    enabled: false
  test-logging:
    enabled: false
  velero:
    enabled: false
  visitor-groups:
    enabled: false
  zeebe:
    enabled: false
  zeebe-operate:
    enabled: false
  kyverno:
    enabled: false
  cluster-policies:
    enabled: false
  kyverno-policies:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  descheduler:
    enabled: false
  cluster-rbac:
    enabled: false
  node-problem-detector:
    enabled: false
  rabbitmq-managed:
    enabled: false
  mongodb-managed:
    enabled: false
  flux-repository:
    enabled: false
  dex:
    enabled: false
  oauth2-proxy:
    enabled: false
  namespace:
    enabled: false
  trivy:
    enabled: false
