### These should be implemented in each project. 
# Keep these up to date to help implementing quickly.

# Global project variables
project:
  name: KUBE_CORE_PROJECT_NAME
  description: KUBE_CORE_PROJECT_DESCRIPTION
  repository: KUBE_CORE_PROJECT_REPOSITORY
  ref: main
  path: /cluster

# Git Repository Info (used to generate git related stuff)
git:
  provider: KUBE_CORE_GIT_PROVIDER
  web: KUBE_CORE_GIT_WEB
  api:
    url: KUBE_CORE_GIT_API_URL
    host: KUBE_CORE_GIT_API_HOST
    token: KUBE_CORE_GIT_API_TOKEN
  ssh:
    url: KUBE_CORE_GIT_SSH_URL
    host: KUBE_CORE_GIT_SSH_HOST
    key: KUBE_CORE_GIT_SSH_KEY
    known_hosts: KUBE_CORE_GIT_SSH_KNOWN_HOSTS
  webhooks:
    token: KUBE_CORE_GIT_WEBHOOKS_TOKEN
  bot:
    user: KUBE_CORE_GIT_BOT_USER
    name: KUBE_CORE_GIT_BOT_NAME

# GitOps Repository Info - Can differ from git repo !
gitops:
  api: KUBE_CORE_GITOPS_API
  ssh: KUBE_CORE_GITOPS_SSH
  web: KUBE_CORE_GITOPS_WEB
  repository: KUBE_CORE_GITOPS_REPOSITORY
  ref: KUBE_CORE_GITOPS_REF
  path: KUBE_CORE_GITOPS_PATH
  refresh: 1m
  ssh_key: KUBE_CORE_GITOPS_SSH_KEY
  autocommit: false

# Cloud Provider information
cloud:
  provider: KUBE_CORE_CLOUD_PROVIDER
  project: KUBE_CORE_CLOUD_PROJECT
  registry:
    hostname: KUBE_CORE_CLOUD_REGISTRY_HOSTNAME
  default: 
    location: KUBE_CORE_CLOUD_DEFAULT_LOCATION


# Cluster configuration
cluster:
  config:
    backups: 
      schedule: "0 12 * * *"
    name: KUBE_CORE_CLUSTER_CONFIG_NAME
    context: KUBE_CORE_CLUSTER_CONFIG_CONTEXT
    domain: KUBE_CORE_CLUSTER_CONFIG_DOMAIN
    additionnalDomains: [] # KUBE_CORE_CLUSTER_CONFIG_ADDITIONNAL_DOMAINS
    cidr: 
    - name: cluster-range
      cidr: KUBE_CORE_CLUSTER_CONFIG_CIDR_CLUSTER_RANGE
    - name: cluster-nat
      cidr: KUBE_CORE_CLUSTER_CONFIG_CIDR_CLUSTER_NAT
    network:
      type: KUBE_CORE_CLUSTER_CONFIG_NETWORK_TYPE
    repository:
      name: KUBE_CORE_CLUSTER_CONFIG_REPOSITORY_NAME
      url: KUBE_CORE_CLUSTER_CONFIG_REPOSITORY_URL
      ref: KUBE_CORE_CLUSTER_CONFIG_REPOSITORY_REF
      path: KUBE_CORE_CLUSTER_CONFIG_REPOSITORY_PATH
    adminEmail: KUBE_CORE_CLUSTER_CONFIG_ADMIN_EMAIL
    schedule: "Mon-Fri 08:00-20:00 Europe/Paris"
    downscalerExcludedNamespaces: "system-tools,namespace-node-affinity"


config:
  path: ./config

helmfile:
  path: ./helmfile.yaml

helmfiles:
  path: ./helmfiles

local:
  path: ./local

build:
  path: ./local/build

localConfig:
  path: ./local/config

crds:
  path: ./local/crds

configmaps:
  path: ./local/configmaps
  
secrets:
  path: ./local/secrets
  cert:
    path: ./local/secrets/sealed-secrets-cert.pem
  
overlays:
  path: ./local/overlays
  
patches:
  path: ./local/patches
  
test:
  path: ./test
  lint:
    config:
      path: ./yamllint.yaml
  audit:
    config:
      path: ./kubeaudit.yaml
  conftest:
    policies:
      path: ./policy/base
  score:
    config:
      path: ./kubescore.yaml
  validate:
    config:
      path: ./kubeval.yaml

run:
  kbld: false

install:
  type: helmfile
  full: false
  flux: false
  gitops: false
  interactive: false
  crds: false
  sealedsecrets: false
  velero: false
  externaldns: false
  gcr: false
  certmanager: false
  tekton: false

cleanup:
  elasticsearch_tests: ./config/efk/efk/charts/elasticsearch/templates/test

utils:
  image: neo9sas/devops-tools:latest