# Cloud Provider Info & Config
cloud:
  provider: KUBE_CORE_CLOUD_PROVIDER
  providerShortName: KUBE_CORE_CLOUD_PROVIDER_SHORT_NAME
  project: KUBE_CORE_CLOUD_PROJECT
  projectShortName: KUBE_CORE_CLOUD_PROJECT_SHORT_NAME
  location:
    name: europe-west1
    shortName: euwe1
    region: europe
    regionShortName: eu
    zone: west
    zoneShortName: we
    zoneId: 1
    zoneIdShortName: 1
  registry:
    hostname: KUBE_CORE_CLOUD_REGISTRY_HOSTNAME
  default:
    location: KUBE_CORE_CLOUD_DEFAULT_LOCATION
  naming:
    enabled: false
    config:
      forceCoreNaming: false
      forceReleaseNaming: false
      forceAutoMergeNaming: false
      templatesEnabled: true
      templates:
        default:
          nameBase: default-pretty
        # custom:
        #   nameBase: default-short
        #   cloudResourcePrefixTemplate: cloud-resource-prefix-full
        #   clusterResourcePrefixTemplate: cluster-resource-prefix-full
    resourceTemplates:
      default-pretty: "{{with .prefixes}}{{.cloudResourcePrefixCompact }}-{{ .clusterResourcePrefixShort }}{{end}}"
      default-full: "{{with .prefixes}}{{.cloudResourcePrefixFull }}-{{ .clusterResourcePrefixFull }}{{end}}"
      default-short: "{{with .prefixes}}{{.cloudResourcePrefixShort }}-{{ .clusterResourcePrefixShort }}{{end}}"

    prefixTemplates:
      cloud-resource-prefix-full: "{{with .cloud.full}}{{.orgName}}-{{.platformName}}-{{.cloudProvider}}-{{.cloudRegion}}-{{.cloudZone}}-{{.cloudZoneId}}{{end}}"
      cloud-resource-prefix-short: "{{with .cloud.short}}{{.orgName}}-{{.platformName}}-{{.cloudProvider}}-{{.cloudRegion}}-{{.cloudZone}}-{{.cloudZoneId}}{{end}}"
      cloud-resource-prefix-compact: "{{with .cloud.short}}{{.orgName}}{{.platformName}}{{.cloudProvider}}{{.cloudRegion}}{{.cloudZone}}{{.cloudZoneId}}{{end}}"
      cloud-resource-prefix-hash: |-
        {{with .cloud.full}}{{ (list .orgName .platformName .cloudProvider .cloudRegion .cloudZone .cloudZoneId) | join "" | sha256sum }}{{end}}

      cluster-resource-prefix-full: "{{with .release.full}}{{.context}}-{{.namespace}}-{{.name}}{{end}}"
      cluster-resource-prefix-short: "{{with .release.short}}{{.context}}-{{.namespace}}-{{.name}}{{end}}"
      cluster-resource-prefix-compact: "{{with .release.short}}{{.context}}{{.namespace}}{{.name}}{{end}}"
      cluster-resource-prefix-hash: |-
        {{with .release.full}}{{ (list .context .namespace .name) | join "" | sha256sum }}{{end}}

    options:
      allowOverrides: false
      forceShortName: false
      forceCompactName: false
      forceHashedName: false
      forceFullName: false

      enableOrgName: false
      enablePlatformName: false
      enableRegion: false
      enableZone: false
      enableLocation: false
      enableAppOrPlatform: false
      enableEnvironment: false
      enableEnvironmentIsNamespace: false
      enableNamespace: false
      enableCloudResourceType: false
      enableResourceFullName: false
      enableResourceShortName: false
      enableResourceCompactName: false
      enableResourceHashedName: false
