# These values must be filled on consumer side !
core:
  releasesEnabled: true
  releasesRawEnabled: true
  releasesCustomEnabled: true
  namespacesEnabled: false
  globalLabelsEnabled: true
  globalHelmMetadataEnabled: true
  applicationsEnabled: false
  servicesEnabled: false
  clusterEnabled: false
  enableCloudMetadataDebug: false
  helmfileName: core
  ha: false
  installCRDs: false
  version: v1.0.0
  packages:
    essentials:
      enabled: false
    logging:
      enabled: false
    monitoring:
      enabled: false
    crossplane:
      enabled: false
    estafette:
      enabled: false
    tekton:
      enabled: false
    kyverno:
      enabled: false
    istio:
      enabled: false
