# Git Provider & Config
git:
  provider: KUBE_CORE_GIT_PROVIDER
  web: KUBE_CORE_GIT_WEB
  github_read_token: ./keys/.github-read-token #KUBE_CORE_GITHUB_READ_TOKEN
  api:
    url: KUBE_CORE_GIT_API_URL
    host: KUBE_CORE_GIT_API_HOST
    token: ./keys/.git-api-token #KUBE_CORE_GIT_API_TOKEN
  ssh:
    url: KUBE_CORE_GIT_SSH_URL
    host: KUBE_CORE_GIT_SSH_HOST
    key: ./keys/.git-ssh-key #KUBE_CORE_GIT_SSH_KEY
    known_hosts: ./keys/.git-ssh-hosts #KUBE_CORE_GIT_SSH_KNOWN_HOSTS
  webhooks:
    token: ./keys/.git-webhooks-token #KUBE_CORE_GIT_WEBHOOKS_TOKEN
  bot:
    user: KUBE_CORE_GIT_BOT_USER
    name: KUBE_CORE_GIT_BOT_NAME
