project:
  name: KUBE_CORE_PROJECT_NAME
  shortName: KUBE_CORE_PROJECT_SHORT_NAME
  description: KUBE_CORE_PROJECT_DESCRIPTION
  repository: KUBE_CORE_PROJECT_REPOSITORY
  ref: KUBE_CORE_PROJECT_REF
  path: KUBE_CORE_PROJECT_PATH
