cluster:
  config:
    corePoliciesEnabled: false
    clusterPoliciesEnabled: false
    backups:
      schedule: "0 12 * * *" #KUBE_CORE_CLUSTER_CONFIG_BACKUPS_SCHEDULE
    name: KUBE_CORE_CLUSTER_CONFIG_NAME
    shortName: KUBE_CORE_CLUSTER_CONFIG_SHORT_NAME
    context: KUBE_CORE_CLUSTER_CONFIG_CONTEXT
    contextShortName: KUBE_CORE_CLUSTER_CONFIG_CONTEXT_SHORT_NAME
    domain: KUBE_CORE_CLUSTER_CONFIG_DOMAIN
    additionnalDomains: [] # KUBE_CORE_CLUSTER_CONFIG_ADDITIONNAL_DOMAINS
    network:
      cluster:
        block: KUBE_CORE_NETWORK_CLUSTER_BLOCK
      type: KUBE_CORE_CLUSTER_CONFIG_NETWORK_TYPE
      master: KUBE_CORE_CLUSTER_CONFIG_NETWORK_MASTER
      cidr:
        cluster:
          range: KUBE_CORE_CLUSTER_CONFIG_CIDR_CLUSTER_RANGE
          nat: KUBE_CORE_CLUSTER_CONFIG_CIDR_CLUSTER_NAT
      vpc:
        subnet: "10.KUBE_CORE_NETWORK_CLUSTER_BLOCK.0.0/24"
        pods: "10.KUBE_CORE_NETWORK_CLUSTER_BLOCK.128.0/17"
        # Range /20 corresponds to 8,192 services
        services: "10.KUBE_CORE_NETWORK_CLUSTER_BLOCK.96.0/19"
        # Private cluster require a dedicated non-overlapping /28 ranges for controlplane
        controlplane: "10.KUBE_CORE_NETWORK_CLUSTER_BLOCK.95.0/28"
      maxPodsPerNode: 64
    repository:
      name: KUBE_CORE_CLUSTER_CONFIG_REPOSITORY_NAME
      url: KUBE_CORE_CLUSTER_CONFIG_REPOSITORY_URL
      ref: KUBE_CORE_CLUSTER_CONFIG_REPOSITORY_REF
      path: KUBE_CORE_CLUSTER_CONFIG_REPOSITORY_PATH
    adminEmail: KUBE_CORE_CLUSTER_CONFIG_ADMIN_EMAIL
    schedule: "Mon-Fri 08:00-20:00 Europe/Paris" #KUBE_CORE_CLUSTER_CONFIG_SCHEDULE
    downscalerExcludedNamespaces: "system-tools,namespace-node-affinity" #KUBE_CORE_CLUSTER_CONFIG_DOWNSCALER_EXCLUDED_NAMESPACES
    extraVisitorGroups: []
