apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cluster-hooks
spec:
  rules:
  - host: {{ (index .Values.tekton.config "cluster-hooks" "ingress" "subdomain") }}.{{ .Values.cluster.config.domain }}
    http:
      paths:
      - backend:
          service:
            name: el-cluster-hooks
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - {{ (index .Values.tekton.config "cluster-hooks" "ingress" "subdomain") }}.{{ .Values.cluster.config.domain }}
    secretName: {{ (index .Values.tekton.config "cluster-hooks" "ingress" "subdomain") | replace "." "-"}}-tls
