apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels: {{ toYaml (.Values.cluster.common.defaultIngressLabels) | nindent 4 }}
  annotations: {{ toYaml (.Values.cluster.common.defaultIngressAnnotations) | nindent 4 }}
  name: kiali
  namespace: istio-system
spec:
  rules:
  - host: kiali.mesh.{{ .Values.cluster.config.domain }}
    http:
      paths:
      - backend:
          serviceName: kiali
          servicePort: 20001
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - kiali.mesh.{{ .Values.cluster.config.domain }}
    secretName: kiali-tls
