#!/bin/bash
set -eou pipefail

## Header Start

# Current Script
currentScript=${BASH_SOURCE[0]}
currentScriptPath="$( cd "$( dirname "${currentScript}" )" >/dev/null 2>&1 && pwd )"
currentScriptShortPath=$(echo "${currentScriptPath}" | awk '{split($0, a, "/scripts/"); print a[2]}')

# Cluster Config
if [[ ! -z $(find ./cluster-config.yaml 2> /dev/null) ]]; then
    clusterConfigPath=$(echo ./cluster-config.yaml | head -n 1 | xargs realpath 2> /dev/null)
else
    clusterConfigPath=$(eval find ./$(printf "{$(echo %{1..7}q,)}" | sed 's/ /\.\.\//g') -maxdepth 1 -name cluster-config.yaml | head -n 1 | xargs realpath 2> /dev/null) || true
fi
if [[ -z "${clusterConfigPath}" ]] ; then
    echo "Stopping ${currentScript}"
    echo "This script requires to be in a cluster context, but cluster-config.yaml not found in parent directories"
    exit 0
fi

clusterConfigDirPath=$(dirname ${clusterConfigPath} | xargs realpath)
helmfilePath="${clusterConfigDirPath}/helmfile.yaml"
tmpFolder="${clusterConfigDirPath}/.kube-core/.tmp"

# Cluster Scripts
if [[ ! -z $(find ${currentScriptPath}/scripts-config.yaml 2> /dev/null) ]]; then
    scriptsConfigPath=$(echo ${currentScriptPath}/scripts-config.yaml | head -n 1 | xargs realpath 2> /dev/null)
else
    scriptsConfigPath=$(eval find "${currentScriptPath}"/$(printf "{$(echo %{1..7}q,)}" | sed 's/ /\.\.\//g') -maxdepth 1 -name scripts-config.yaml | head -n 1 | xargs realpath)
fi
scriptsConfigDirPath=$(dirname ${scriptsConfigPath} | xargs realpath)

defaultClusterConfigPath=${scriptsConfigDirPath}/default-cluster-config.yaml
corePath=$(echo ${scriptsConfigDirPath}/.. | xargs realpath)
coreTmpFolder="${corePath}/.kube-core/.tmp"

# Loading scripts
eval "$(${scriptsConfigDirPath}/src/includes.sh)"

# Loading default-cluster-config.yaml
clusterConfigVars=$(parse_yaml ${defaultClusterConfigPath})
clusterConfigVars=$(echo "${clusterConfigVars}" | sed "s|\./|${clusterConfigDirPath}/|")
eval "${clusterConfigVars}"

# Loading cluster-config.yaml
clusterConfigVars=$(parse_yaml ${clusterConfigPath})
clusterConfigVars=$(echo "${clusterConfigVars}" | sed "s|\./|${clusterConfigDirPath}/|")
eval "${clusterConfigVars}"

# Loading scripts-config.yaml
paths=$(parse_yaml ${scriptsConfigPath})
absolutePaths=$(echo "${paths}" | sed "s|\./|${scriptsConfigDirPath}/|")
eval "${absolutePaths}"

check_requirements
prepare_workspace
check_context "${cluster_config_context}"
# check_args "$@"
## Header End


log_info "Building: local/config -> config..."

tmpConfigPath=${tmpFolder}/config
configPath=${tmpConfigPath}
localConfigPath=${localConfig_path}
buildPath=${build_path}

# Runs all build.sh scripts in sub-folders of local/build (ex: local/build/my-awesome-script-to-generate-deployments/build.sh)
# Then copies to gitops config all the files placed in "generated" folder (ex: local/build/my-awesome-script-to-generate-deployments/generated/deployments.yaml)
find ${buildPath} -mindepth 1 -maxdepth 1 -type d | while read currentPath; do

    resource=$(basename $currentPath)
    sourceManifestsPath=${buildPath}/${resource}/generated
    targetManifestsPath=${configPath}

    log_debug "$resource"

    rm -rf ${sourceManifestsPath}
    mkdir -p ${sourceManifestsPath}

    ${currentPath}/generate.sh
    
    mkdir -p ${targetManifestsPath}

    # Here we use -nr to make sure that it is NOT possible to overwrite manifests generated by Helmfile via local/config
    # TODO: Decide if this is good or if we prefer to have overwrite by default (or a flag to choose)
    # cp -nr ${sourceManifestsPath}/* ${targetManifestsPath} 2>/dev/null || true
    cp -fr ${sourceManifestsPath}/* ${targetManifestsPath} 2>/dev/null || true
        
done;


# Copies all files from local config to cluster config
find ${localConfigPath} -mindepth 1 -maxdepth 1 -type d | while read currentPath; do

    resource=$(basename $currentPath)
    sourceManifestsPath=${localConfigPath}/
    targetManifestsPath=${configPath}/${resource}
    
    log_debug "${resource}: copying files"

    # Copying files without replacing existing
    mkdir -p ${targetManifestsPath}
    # echo ${sourceManifestsPath} ${configPath}

    # Here we use -nr to make sure that it is NOT possible to overwrite manifests generated by Helmfile via local/config
    # TODO: Decide if this is good or if we prefer to have overwrite by default (or a flag to choose)
    # cp -nr ${sourceManifestsPath}/* ${configPath} 2>/dev/null || true
    cp -fr ${sourceManifestsPath}/* ${configPath} 2>/dev/null || true
    
done;

log_info "Done Building: local/config -> config"
