cluster:
  logging:
    flows:
      flows:
      - name: app
      - name: cluster
    integrations:
      es:
        enabled: true
    stack:
      es:
        nodes:
          storageClass: gcp-sc-retain-wait-ssd
          affinity: {}
          nodeSelector: {}
          tolerations:
          - key: "type"
            operator: "Equal"
            value: "search"
            effect: "NoSchedule"
          - key: "type"
            operator: "Equal"
            value: "search"
            effect: "NoExecute"
          - key: "type"
            operator: "Equal"
            value: "logging"
            effect: "NoSchedule"
          - key: "type"
            operator: "Equal"
            value: "logging"
            effect: "NoExecute"
          - key: "type"
            operator: "Equal"
            value: "monitoring"
            effect: "NoSchedule"
          - key: "type"
            operator: "Equal"
            value: "monitoring"
            effect: "NoExecute"
      kibana:
        enabled: true
      minio:
        enabled: true
      fluentd:
        buffer:
          storageClass: gcp-sc-retain-wait-ssd
        tolerations:
        - key: "type"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
        - key: "type"
          operator: "Equal"
          value: "monitoring"
          effect: "NoExecute"
        affinity: {}
      fluentbit:
        enabled: true
        tolerations:
        - key: "type"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
        - key: "type"
          operator: "Equal"
          value: "monitoring"
          effect: "NoExecute"
        - key: "type"
          operator: "Equal"
          value: "production"
          effect: "NoSchedule"
        - key: "type"
          operator: "Equal"
          value: "production"
          effect: "NoExecute"
        # - key: "type"
        #   operator: "Equal"
        #   value: "system"
        #   effect: "NoSchedule"
        # - key: "type"
        #   operator: "Equal"
        #   value: "system"
        #   effect: "NoExecute"
        affinity: {}
