apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels: {{ toYaml (.Values.cluster.common.defaultIngressLabels) | nindent 4 }}
  annotations: {{ toYaml (.Values.cluster.common.defaultIngressAnnotations) | nindent 4 }}
  name: prometheus
  namespace: istio-system
spec:
  ingressClassName: {{ .Values.cluster.common.defaultIngressClass }}
  rules:
  - host: prometheus.istio-system.{{ .Values.cluster.config.domain }}
    http:
      paths:
      - backend:
          service:
            name: prometheus
            port:
              number: 9090
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - prometheus.istio-system.{{ .Values.cluster.config.domain }}
    secretName: prometheus-tls
