{{- define "crossplane-cloud.serviceaccount" -}}
{{ $name := (coalesce .value.name .key) }}
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  annotations:
    crossplane.io/external-name: {{ coalesce .value.externalName $name }}
spec:
  deletionPolicy: {{ coalesce .value.deletionPolicy "Orphan" }}
  forProvider:
    displayName: {{ coalesce .value.displayName $name }}
    description: "{{ coalesce .value.description (printf "SA generated by kube-core for: %s/%s/%s" .value.clusterName .value.namespace ( coalesce .value.mainReleaseName $name)) }}"
  providerConfigRef:
    name: gcp
{{- end }}

{{- define "crossplane-cloud.serviceaccountpolicy" -}}
{{ $name := (coalesce .value.name .key) }}
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccountPolicy
metadata:
  name: {{ $name }}
  annotations:
    crossplane.io/external-name: {{ coalesce .value.externalName $name }}
spec:
  deletionPolicy: {{ coalesce .value.deletionPolicy "Orphan" }}
  forProvider:
    serviceAccountRef:
      name: {{ coalesce $.value.sa $name }}
    policy:
      bindings:
      {{- if (not (eq (.value.defaultRole) false)) }}
      - role: {{ coalesce .value.role (printf "projects/%s/roles/%s" .project $name) }}
        serviceAccountMemberRefs:
        - name: {{ coalesce .value.sa $name }}
      {{ end }}
      {{- if .value.defaultRoles }}
      {{ range .value.defaultRoles }}
      - role: {{ . }}
        serviceAccountMemberRefs:
        - name: {{ coalesce $.value.sa $name }}
      {{ end }}
      {{ end }}
      {{- if .value.roles }}
      {{- range .value.roles }}
      - {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ end }}
  providerConfigRef:
    name: gcp
{{- end }}


{{- define "crossplane-cloud.serviceaccountkey" -}}
{{ $name := (coalesce .value.name .key) }}
apiVersion: iam.gcp.crossplane.io/v1alpha1
kind: ServiceAccountKey
metadata:
  name: {{ $name }}
  # annotations:
  #   crossplane.io/external-name: {{ coalesce .value.externalName $name }}
spec:
  deletionPolicy: {{ coalesce .value.deletionPolicy "Orphan" }}
  forProvider:
    serviceAccountRef:
      name: {{ coalesce .value.externalName $name }}
  publishConnectionDetailsTo:
    name: {{ coalesce .value.externalName $name }}
    {{- if .value.metadata }}
    metadata: {{ toYaml .value.metadata | nindent 6 }}
    {{ else }}
    metadata:
      annotations:
        replicator.v1.mittwald.de/replication-allowed: "true"
        replicator.v1.mittwald.de/replication-allowed-namespaces: "*"
    {{ end }}
  providerConfigRef:
    name: gcp
{{- end }}

{{- define "crossplane-cloud.bucket" -}}
{{ $name := (coalesce .value.name .key) }}
apiVersion: storage.gcp.crossplane.io/v1alpha3
kind: Bucket
metadata:
  name: {{ $name }}
  annotations:
    crossplane.io/external-name: {{ coalesce .value.externalName $name }}
spec:
  deletionPolicy: {{ coalesce .value.deletionPolicy "Orphan" }}
  location: {{ .value.location }}
  {{- if (.value.uniformPolicy | default true) }}
  bucketPolicyOnly:
    enabled: true
  {{- end }}
  labels:
    managed-by: "crossplane"
    cluster: {{ .value.clusterName }}
    {{- if .value.labels }}
    {{ toYaml (.value.labels) | nindent 4 }}
    {{- end }}
  providerConfigRef:
    name: gcp
{{- end }}

{{- define "crossplane-cloud.bucketpolicy" -}}
{{ $name := (coalesce .value.name .key) }}
apiVersion: storage.gcp.crossplane.io/v1alpha1
kind: BucketPolicy
metadata:
  name: {{ $name }}
  annotations:
    crossplane.io/external-name: {{ coalesce .value.externalName $name }}
spec:
  deletionPolicy: {{ coalesce .value.deletionPolicy "Orphan" }}
  forProvider:
    bucketRef:
      name: {{ coalesce .value.bucketRef $name }}
    policy:
      bindings:
      {{- if .value.public | default false }}
      - role: roles/storage.objectViewer
        members:
        - allUsers
      {{ end }}
      {{- if (not (eq .value.admin false)) }}
      - role: roles/storage.objectAdmin
        serviceAccountMemberRefs:
        - name: {{ coalesce .value.adminRef $name }}
      {{ end }}
      {{- if .value.roles }}
      {{- range .value.roles }}
      - {{ toYaml . | nindent 8 }}
      {{ end }}
      {{ end }}
  providerConfigRef:
    name: gcp
{{- end }}

{{- define "crossplane-cloud.serviceaccountiammember" -}}
{{ $name := (coalesce .value.name .key) }}
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ServiceAccountIAMMember
metadata:
  name: {{ $name }}
  annotations:
    crossplane.io/external-name: {{ coalesce .value.externalName $name }}
spec:
  deletionPolicy: {{ coalesce .value.deletionPolicy "Orphan" }}
  forProvider:
    member: serviceAccount:{{ $name }}@{{.project}}.iam.gserviceaccount.com
    role: {{ coalesce .value.role (printf "projects/%s/roles/%s" .project $name) }}
    serviceAccountIdRef:
      name: {{ coalesce .value.sa $name }}
  providerConfigRef:
    name: upbound-gcp
{{- end }}

{{- define "crossplane-cloud.projectiammember" -}}
{{ $name := (coalesce .value.name .key) }}
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: ProjectIAMMember
metadata:
  name: {{ $name }}
  annotations:
    crossplane.io/external-name: {{ coalesce .value.externalName $name }}
spec:
  deletionPolicy: {{ coalesce .value.deletionPolicy "Orphan" }}
  forProvider:
    member: serviceAccount:{{ coalesce .value.member $name }}@{{ .value.project }}.iam.gserviceaccount.com
    project: {{ .value.project }}
    role: {{ coalesce .value.role (printf "projects/%s/roles/%s" .value.project ($name | kebabcase | replace "-" "." | untitle)) }}
  providerConfigRef:
    name: upbound-gcp
{{- end }}

{{- define "crossplane-cloud.projectiamcustomrole" -}}
{{ $name := (coalesce .value.name .key) }}
apiVersion: cloudplatform.gcp.jet.crossplane.io/v1alpha1
kind: ProjectIAMCustomRole
metadata:
  name: {{ $name }}
  annotations:
    crossplane.io/external-name: projects/{{.value.project}}/roles/{{ coalesce .value.externalName $name }}
spec:
  deletionPolicy: {{ coalesce .value.deletionPolicy "Orphan" }}
  forProvider:
    project: {{ required "Project is required for ProjectIAMCustomRole" .value.project }}
    permissions: {{ toYaml .value.permissions | nindent 4 }}
    roleId: {{ coalesce .value.externalName $name }}
    title: {{ coalesce .value.title $name }}
  providerConfigRef:
    name: jet-gcp
{{- end }}
