# Cloud Provider Info & Config
cloud:
  enabled: false
  provider: KUBE_CORE_CLOUD_PROVIDER
  providerShortName: KUBE_CORE_CLOUD_PROVIDER_SHORT_NAME
  project: KUBE_CORE_CLOUD_PROJECT
  projectShortName: KUBE_CORE_CLOUD_PROJECT_SHORT_NAME
  location:
    name: europe-west1
    shortName: euwe1
    region: europe
    regionShortName: eu
    zone: west
    zoneShortName: we
    zoneId: 1
    zoneIdShortName: 1
  registry:
    hostname: KUBE_CORE_CLOUD_REGISTRY_HOSTNAME
  default:
    location: KUBE_CORE_CLOUD_DEFAULT_LOCATION
  crossplane:
    defaultDeletionPolicy: Orphan
  naming:
    namespaceShortNames:
      dev: dev
      integration: int
      validation: val
      staging: stg
      preproduction: ppd
      production: prd
      prod: prd
    config:
      forceCoreNaming: false
      forceReleaseNaming: false
      forceAutoMergeNaming: false
      templates:
        default:
          nameBase: default-pretty
          serviceAccountName: kube-core-serviceAccount
          serviceAccountKeyName: kube-core-serviceAccount
          bucketName: kube-core-default-localized
          bucketPolicyName: kube-core-default-localized
          backendBucketName: kube-core-default-localized
          iamMemberName: kube-core-default
          iamRoleName: kube-core-default
          iamRoleExternalName: kube-core-iamRoleExternal
          globalAddressName: kube-core-default-localized
          globalForwardingRuleName: kube-core-default-localized
          targetHttpProxyName: kube-core-default-localized
          targetHttpsProxyName: kube-core-default-localized
          urlMapName: kube-core-default-localized
          managedSslCertificateName: kube-core-default
        # custom:
        #   nameBase: default-short
        #   cloudResourcePrefixTemplate: cloud-resource-prefix-full
        #   clusterResourcePrefixTemplate: cluster-resource-prefix-full

    resourceTemplates:
      default-pretty: "{{with .prefixes}}{{.cloudResourcePrefixCompact }}-{{ .clusterResourcePrefixShort }}{{end}}"
      default-full: "{{with .prefixes}}{{.cloudResourcePrefixFull }}-{{ .clusterResourcePrefixFull }}{{end}}"
      default-short: "{{with .prefixes}}{{.cloudResourcePrefixShort }}-{{ .clusterResourcePrefixShort }}{{end}}"

      kube-core-default: "{{with .prefixes}}{{.kubeCoreCloudPrefixShort }}-{{.kubeCoreClusterReleaseShort }}-{{ .kubeCoreClusterResourceIdShort }}{{end}}"
      kube-core-default-localized: "{{with .prefixes}}{{.kubeCoreCloudPrefixShort }}-{{.kubeCoreClusterReleaseShort }}-{{ .kubeCoreClusterResourceIdShort }}-{{.kubeCoreCloudLocationCompact}}{{end}}"
      kube-core-serviceAccount: "{{with .prefixes}}{{.kubeCoreClusterReleaseShort }}-{{ .kubeCoreClusterResourceIdShort }}{{end}}"
      kube-core-iamRoleExternal: |-
        {{with .prefixes}}{{ printf "%s.%s.%s" .kubeCoreCloudPrefixShort .kubeCoreClusterReleaseShort .kubeCoreClusterResourceIdShort | replace "-" "."}}{{end}}

    prefixTemplates:
      kube-core-cloud-prefix-short: "{{with .cloud.short}}{{.orgName}}-{{.cloudProject}}{{end}}"
      kube-core-cloud-location-compact: "{{with .cloud.short}}{{.cloudRegion}}{{.cloudZone}}{{.cloudZoneId}}{{end}}"
      kube-core-cluster-release-short: |-
        {{.release.short.appOrPlatform}}-{{if eq .release.short.appOrPlatform "p"}}{{.cloud.short.clusterName}}-{{end}}{{.release.short.namespace}}
      kube-core-cluster-resource-id-short: "{{with .release.short}}{{.name}}{{end}}"

      # default-serviceAccount: ""
      # default-serviceAccountKey: ""
      # default-bucket: ""
      # default-bucketPolicy: ""
      # default-backendBucket: ""
      # default-iamMember: ""
      # default-iamRole: ""
      # default-globalAddress: ""
      # default-globalForwardingRule: ""
      # default-targetHttpProxy: ""
      # default-targetHttpsProxy: ""
      # default-urlMap: ""
      # default-managedSslCertificate: ""
      cloud-resource-prefix-full: "{{with .cloud.full}}{{.orgName}}-{{.platformName}}-{{.cloudProvider}}-{{.cloudRegion}}-{{.cloudZone}}-{{.cloudZoneId}}{{end}}"
      cloud-resource-prefix-short: "{{with .cloud.short}}{{.orgName}}-{{.platformName}}-{{.cloudProvider}}-{{.cloudRegion}}-{{.cloudZone}}-{{.cloudZoneId}}{{end}}"
      cloud-resource-prefix-compact: "{{with .cloud.short}}{{.orgName}}{{.platformName}}{{.cloudProvider}}{{.cloudRegion}}{{.cloudZone}}{{.cloudZoneId}}{{end}}"
      cloud-resource-prefix-hash: |-
        {{with .cloud.full}}{{ (list .orgName .platformName .cloudProvider .cloudRegion .cloudZone .cloudZoneId) | join "" | sha256sum }}{{end}}

      cluster-resource-prefix-full: "{{with .release.full}}{{.context}}-{{.namespace}}-{{.name}}{{end}}"
      cluster-resource-prefix-short: "{{with .release.short}}{{.context}}-{{.namespace}}-{{.name}}{{end}}"
      cluster-resource-prefix-compact: "{{with .release.short}}{{.context}}{{.namespace}}{{.name}}{{end}}"
      cluster-resource-prefix-hash: |-
        {{with .release.full}}{{ (list .context .namespace .name) | join "" | sha256sum }}{{end}}

    options:
      allowOverrides: false
      forceShortName: false
      forceCompactName: false
      forceHashedName: false
      forceFullName: false

      enableOrgName: false
      enablePlatformName: false
      enableRegion: false
      enableZone: false
      enableLocation: false
      enableAppOrPlatform: false
      enableEnvironment: false
      enableEnvironmentIsNamespace: false
      enableNamespace: false
      enableCloudResourceType: false
      enableResourceFullName: false
      enableResourceShortName: false
      enableResourceCompactName: false
      enableResourceHashedName: false
