platform:
  name: KUBE_CORE_PLATFORM_NAME
  shortName: KUBE_CORE_PLATFORM_SHORT_NAME
  description: KUBE_CORE_PLATFORM_DESCRIPTION
  repository: KUBE_CORE_PLATFORM_REPOSITORY
  ref: KUBE_CORE_PLATFORM_REF
  path: KUBE_CORE_PLATFORM_PATH
